services:

  leader:
    container_name: edgar-leader  # defined DNS for the container
    build:
      context: ../../..
      dockerfile: ./.ci/docker/edgar/Dockerfile
    command: /opt/managed.sh leader
    #command: sleep infinity
    volumes:
      - ../../../target/ci/distribution/x86_64-unknown-linux-gnu/:/opt/artifacts
      - "../../../.ci/deploy/localenv/data/secrets/pki/insecure-development-ca.pem:/etc/opendut/tls/ca.pem"
      - "../../../.ci/deploy/localenv/data/secrets/pki/insecure-development-ca.pem:/usr/local/share/ca-certificates/ca.pem"
    cap_add:
      - NET_ADMIN
    environment:
      # CLEO
      - OPENDUT_CLEO_NETWORK_CARL_HOST
      - OPENDUT_CLEO_NETWORK_CARL_PORT=443
      - OPENDUT_CLEO_NETWORK_TLS_DOMAIN_NAME_OVERRIDE  # default developer certificate is only valid for localhost
      - OPENDUT_CLEO_NETWORK_OIDC_ENABLED=true
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_ID=opendut-cleo-client
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_SECRET
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_ISSUER_URL
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_SCOPES=
      - OPENDUT_CLEO_NETWORK_TLS_CA=/etc/opendut/tls/ca.pem
      - SSL_CERT_FILE=/etc/opendut/tls/ca.pem

      # EDGAR
      - OPENDUT_EDGAR_NETWORK_CARL_HOST
      - OPENDUT_EDGAR_NETWORK_CARL_PORT=443
      - OPENDUT_EDGAR_NETWORK_TLS_DOMAIN_NAME_OVERRIDE  # default developer certificate is only valid for localhost
      - OPENDUT_EDGAR_NETWORK_OIDC_ENABLED=true
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_ID=opendut-edgar-client
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_SECRET
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_ISSUER_URL
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_SCOPES=
      - OPENDUT_EDGAR_OPENTELEMETRY_ENABLED=false

      # Netbird
      - NETBIRD_MANAGEMENT_API

      # testenv
      - NETBIRD_GROUP=testenv  # only used by unmanaged mode
      - OPENDUT_EDGAR_REPLICAS
      - OPENDUT_EDGAR_SERVICE_USER=root
      - OPENDUT_EDGAR_CLUSTER_NAME

      # Rust backtrace
      - RUST_BACKTRACE=1

    networks:
      - opendutnet

  peer:
    build:
      context: ../../..
      dockerfile: ./.ci/docker/edgar/Dockerfile
    command: /opt/managed.sh
    #command: sleep infinity
    volumes:
      - ../../../target/ci/distribution/x86_64-unknown-linux-gnu/:/opt/artifacts:ro
      - "../../../.ci/deploy/localenv/data/secrets/pki/insecure-development-ca.pem:/etc/opendut/tls/ca.pem"
      - "../../../.ci/deploy/localenv/data/secrets/pki/insecure-development-ca.pem:/usr/local/share/ca-certificates/ca.pem"
    cap_add:
      - NET_ADMIN
    environment:
      # CLEO
      - OPENDUT_CLEO_NETWORK_CARL_HOST
      - OPENDUT_CLEO_NETWORK_CARL_PORT=443
      - OPENDUT_CLEO_NETWORK_TLS_DOMAIN_NAME_OVERRIDE  # default developer certificate is only valid for localhost
      - OPENDUT_CLEO_NETWORK_OIDC_ENABLED=true
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_ID=opendut-cleo-client
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_SECRET
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_ISSUER_URL
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_SCOPES=
      - OPENDUT_CLEO_NETWORK_TLS_CA=/etc/opendut/tls/ca.pem
      - SSL_CERT_FILE=/etc/opendut/tls/ca.pem

      # EDGAR
      - OPENDUT_EDGAR_NETWORK_CARL_HOST
      - OPENDUT_EDGAR_NETWORK_CARL_PORT=443
      - OPENDUT_EDGAR_NETWORK_TLS_DOMAIN_NAME_OVERRIDE  # default developer certificate is only valid for localhost
      - OPENDUT_EDGAR_NETWORK_OIDC_ENABLED=true
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_ID=opendut-edgar-client
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_SECRET
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_ISSUER_URL
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_SCOPES=
      - OPENDUT_EDGAR_OPENTELEMETRY_ENABLED=false

      # Netbird
      - NETBIRD_MANAGEMENT_API

      # testenv
      - NETBIRD_GROUP=testenv  # only used by unmanaged mode
      - OPENDUT_EDGAR_REPLICAS
      - OPENDUT_EDGAR_SERVICE_USER=root
      - OPENDUT_EDGAR_CLUSTER_NAME

      # Rust backtrace
      - RUST_BACKTRACE=1

    deploy:
      mode: replicated
      # edgar replica count (e.g. 3)
      replicas: ${OPENDUT_EDGAR_REPLICAS}
    networks:
      - opendutnet

networks:
  opendutnet:
    name: $OPENDUT_DOCKER_NETWORK     # Name of the network
    external: true  # Use a pre-existing network
