name: homepage
on:
  workflow_dispatch:  # manual trigger
    inputs:
      run-testenv:
        description: "Run the build and deployment process of the OpenDuT homepage."
        required: false
        type: string
        default: "false"
  pull_request:
    types: [ opened, reopened, synchronize, edited, ready_for_review ]
  push:
    branches: [
      "main",
      "development"
    ]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*
      - canary

jobs:
  homepage:
    uses: ./.github/workflows/job-homepage.yaml
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      runs-on: "${{ vars.OPENDUT_GH_RUNNER_LARGE || '[\"ubuntu-latest\"]' }}"