name: test
on:
  workflow_call:  # allow this workflow to be called from other workflows
    inputs:
      runs-on:
        default: "['ubuntu-latest']"
        required: false
        type: string

jobs:
  test:
    name: Test and Verify
    runs-on: ${{ fromJson(inputs.runs-on) }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b #4.1.5
      - name: Rust setup
        uses: ./.github/actions/rust-setup
        with:
          cargo-tarpaulin: true

      - name: Test with Coverage
        run: cargo ci coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8
        with:
          name: opendut-coverage
          path: ./target/ci/coverage/
          if-no-files-found: error
          retention-days: 30
