name: homepage
on:
  workflow_call:  # allow this workflow to be called from other workflows
    inputs:
      runs-on:
        default: "['ubuntu-latest']"
        required: false
        type: string

permissions:
  contents: write
  pages: write

jobs:
  check_documentation_changed:
    name: Check if documentation has changed and a new deploy is needed
    runs-on: ${{ fromJson(inputs.runs-on) }}
    outputs:
      documentation: ${{ steps.filter.outputs.documentation }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # https://github.com/dorny/paths-filter/tree/v3.0.2
        id: filter
        with:
          filters: |
            documentation:
              - 'doc/**'
              - 'opendut-homepage/**'

  homepage_build_deploy: # Triggered if pushed on Main, Development or when tagged, also triggered if something changed in doc folder or in opendut-homapge folder
    name: Build and deploy homepage (Push on Main, Development or when tagged)
    needs: check_documentation_changed
    runs-on: ${{ fromJson(inputs.runs-on) }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Rust setup
        uses: ./.github/actions/rust-setup
        with:
          cargo-deny: true
      - name: Build homepage
        run: cargo ci doc homepage build
      - name: Upload homepage artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8
        with:
          name: "homepage"
          path: "./target/ci/homepage"
          if-no-files-found: error
          retention-days: 1
      - name: Prepare branch and commit
#        if: ${{ needs.check_documentation_changed.outputs.documentation == 'true' && (github.ref_name == 'main' || github.ref_name == 'development' || github.ref_type == 'tag') }}
        run: |
          cd /home/runner/work/opendut/opendut
          git fetch --all
          git config alias.switchorcreateorphan '!f() { git switch $1 2>/dev/null && git pull && echo "SWITCHED" || git checkout --orphan $1; && echo "ORPHAN" }; f'
          git switchorcreateorphan github-pages 
          find ./ -mindepth 1 ! -regex '\(^./.git\(/.*\)?\)\|\(^./target\(/.*\)?\)\|\(^./.github\(/.*\)?\)' -delete
          find ./.github/actions -mindepth 1 ! -regex '^./.github/actions/rust-setup\(/.*\)?' -delete 
          ls -la /home/runner/work/opendut/opendut/
          ls -la /home/runner/work/opendut/opendut/.github/actions
          ls -la /home/runner/work/opendut/opendut/.github/actions/rust-setup/
          ls -la /home/runner/work/opendut/opendut/target/ci/homepage
          cp --recursive --update /home/runner/work/opendut/opendut/target/ci/homepage/. /home/runner/work/opendut/opendut/
          ls -la /home/runner/work/opendut/opendut/
          echo "target/" >> .gitignore
          git add -A
          ls -la /home/runner/work/opendut/opendut/
          git config alias.commitordonothing '!f() { git commit -m "Push homepage" 2>/dev/null || echo "Nothing to commit."; }; f'
          git commitordonothing
          git push -u origin github-pages
